### ISSUE TITLE
Task :react-native-webview:compileDebugKotlin FAILED

### ISSUE THREAD

**Issue by rutvikER1999** [react-native-webview/react-native-webview#2601]
### Isuue ###
**Task :react-native-webview:compileDebugKotlin FAILED**

"important info"
OS: "Windows 11"
"react-native-webview": "11.22.7"
"react": "18.0.0"
"react-native": "^0.69.1"

**here is my pckages:** 

- [ ] `"@react-navigation/bottom-tabs": "^6.3.1",
- [ ]     "@react-navigation/drawer": "^5.12.9",
- [ ]     "@react-navigation/native": "^6.0.10",
- [ ]     "@react-navigation/native-stack": "^6.6.2",
- [ ]     "@react-navigation/stack": "^6.2.1",
- [ ]     "react": "18.0.0",
- [ ]     "react-native": "^0.69.1",
- [ ]     "react-native-dotenv": "^3.3.1",
- [ ]     "react-native-flatlist-slider": "^1.0.6",
- [ ]     "react-native-gesture-handler": "^2.5.0",
- [ ]     "react-native-image-slider-box": "^1.1.24",
- [ ]     "react-native-lottie-splash-screen": "^0.1.14",
- [ ]     "react-native-reanimated": "^2.9.1",
- [ ]     "react-native-safe-area-context": "^4.3.1",
- [ ]     "react-native-screens": "^3.14.0",
- [ ]     "react-native-table-component": "^1.2.2",
- [ ]     "react-native-vector-icons": "^9.2.0",
- [ ]     "react-native-video": "6.0.0-alpha.1",
- [ ]     "react-native-webview": "11.22.7"`

**here is my build.gradle**
`

import org.apache.tools.ant.taskdefs.condition.Os

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31

        if (System.properties['os.arch'] == "aarch64") {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = "24.0.8215888"
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = "21.4.7075529"
        }
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.1.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("de.undercouch:gradle-download-task:5.0.1")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
        google()
        maven { url 'https://www.jitpack.io' }
    }
}
`

**here is my error logs**

> 
> > Configure project :react-native-reanimated
> AAR for react-native-reanimated has been found
> C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\react-native-reanimated\android\react-native-reanimated-69-jsc.aar
> 
> > Task :react-native-webview:compileDebugKotlin FAILED
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
> 
> You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> 
> See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
> 120 actionable tasks: 3 executed, 117 up-to-date
> e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
> e: C:/Users/rutvik/.gradle/caches/transforms-3/347daadc4577e97ea182fd1bbd88604c/transformed/jetified-kotlin-stdlib-1.6.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
> e: C:/Users/rutvik/.gradle/caches/transforms-3/93284af1ff4aef981299aa5f71aeea44/transformed/jetified-kotlin-stdlib-jdk8-1.6.10.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
> e: C:/Users/rutvik/.gradle/caches/transforms-3/c31e8d21c519bec0fb80f130fce46632/transformed/jetified-kotlin-stdlib-common-1.6.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
> e: C:/Users/rutvik/.gradle/caches/transforms-3/c8f1e961def0f225a6a5b7efeaa9225e/transformed/jetified-react-native-0.69.1-debug-api.jar!/META-INF/ReactAndroid_debug.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
> e: C:/Users/rutvik/.gradle/caches/transforms-3/d513ea33b864f72616712d89ad44f7df/transformed/jetified-kotlin-stdlib-jdk7-1.6.10.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
> e: C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewPackage.kt: (8, 77): Unresolved reference: listOf
> e: C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewPackage.kt: (12, 76): Unresolved reference: listOf
> e: C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\events\TopHttpErrorEvent.kt: (23, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
> The class is loaded from C:/Users/rutvik/.gradle/caches/transforms-3/347daadc4577e97ea182fd1bbd88604c/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
> e: C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\events\TopLoadingErrorEvent.kt: (23, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
> The class is loaded from C:/Users/rutvik/.gradle/caches/transforms-3/347daadc4577e97ea182fd1bbd88604c/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class     
> e: C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\events\TopLoadingFinishEvent.kt: (23, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
> The class is loaded from C:/Users/rutvik/.gradle/caches/transforms-3/347daadc4577e97ea182fd1bbd88604c/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class     
> e: C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\events\TopLoadingProgressEvent.kt: (23, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
> The class is loaded from C:/Users/rutvik/.gradle/caches/transforms-3/347daadc4577e97ea182fd1bbd88604c/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class     
> e: C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\events\TopLoadingStartEvent.kt: (23, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
> The class is loaded from C:/Users/rutvik/.gradle/caches/transforms-3/347daadc4577e97ea182fd1bbd88604c/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class     
> e: C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\events\TopMessageEvent.kt: (22, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
> The class is loaded from C:/Users/rutvik/.gradle/caches/transforms-3/347daadc4577e97ea182fd1bbd88604c/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class     
> e: C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\events\TopRenderProcessGoneEvent.kt: (24, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.        
> The class is loaded from C:/Users/rutvik/.gradle/caches/transforms-3/347daadc4577e97ea182fd1bbd88604c/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class     
> e: C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\events\TopShouldStartLoadWithRequestEvent.kt: (16, 11): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
> The class is loaded from C:/Users/rutvik/.gradle/caches/transforms-3/347daadc4577e97ea182fd1bbd88604c/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class     
> e: C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\events\TopShouldStartLoadWithRequestEvent.kt: (18, 11): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
> The class is loaded from C:/Users/rutvik/.gradle/caches/transforms-3/347daadc4577e97ea182fd1bbd88604c/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class     
> e: C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\events\TopShouldStartLoadWithRequestEvent.kt: (28, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
> The class is loaded from C:/Users/rutvik/.gradle/caches/transforms-3/347daadc4577e97ea182fd1bbd88604c/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class     
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':react-native-webview:compileDebugKotlin'.
> > Compilation error. See log for more details
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 27s
> 
> error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
> Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
> e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
> e: C:/Users/rutvik/.gradle/caches/transforms-3/347daadc4577e97ea182fd1bbd88604c/transformed/jetified-kotlin-stdlib-1.6.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
> e: C:/Users/rutvik/.gradle/caches/transforms-3/93284af1ff4aef981299aa5f71aeea44/transformed/jetified-kotlin-stdlib-jdk8-1.6.10.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
> e: C:/Users/rutvik/.gradle/caches/transforms-3/c31e8d21c519bec0fb80f130fce46632/transformed/jetified-kotlin-stdlib-common-1.6.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
> e: C:/Users/rutvik/.gradle/caches/transforms-3/c8f1e961def0f225a6a5b7efeaa9225e/transformed/jetified-react-native-0.69.1-debug-api.jar!/META-INF/ReactAndroid_debug.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
> e: C:/Users/rutvik/.gradle/caches/transforms-3/d513ea33b864f72616712d89ad44f7df/transformed/jetified-kotlin-stdlib-jdk7-1.6.10.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
> e: C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewPackage.kt: (8, 77): Unresolved reference: listOf
> e: C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewPackage.kt: (12, 76): Unresolved reference: listOf
> e: C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\events\TopHttpErrorEvent.kt: (23, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
> The class is loaded from C:/Users/rutvik/.gradle/caches/transforms-3/347daadc4577e97ea182fd1bbd88604c/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class     
> e: C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\events\TopLoadingErrorEvent.kt: (23, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
> The class is loaded from C:/Users/rutvik/.gradle/caches/transforms-3/347daadc4577e97ea182fd1bbd88604c/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class     
> e: C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\events\TopLoadingFinishEvent.kt: (23, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
> The class is loaded from C:/Users/rutvik/.gradle/caches/transforms-3/347daadc4577e97ea182fd1bbd88604c/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class     
> e: C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\events\TopLoadingProgressEvent.kt: (23, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
> The class is loaded from C:/Users/rutvik/.gradle/caches/transforms-3/347daadc4577e97ea182fd1bbd88604c/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class     
> e: C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\events\TopLoadingStartEvent.kt: (23, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
> The class is loaded from C:/Users/rutvik/.gradle/caches/transforms-3/347daadc4577e97ea182fd1bbd88604c/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class     
> e: C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\events\TopMessageEvent.kt: (22, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
> The class is loaded from C:/Users/rutvik/.gradle/caches/transforms-3/347daadc4577e97ea182fd1bbd88604c/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class     
> e: C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\events\TopRenderProcessGoneEvent.kt: (24, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.        
> The class is loaded from C:/Users/rutvik/.gradle/caches/transforms-3/347daadc4577e97ea182fd1bbd88604c/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class     
> e: C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\events\TopShouldStartLoadWithRequestEvent.kt: (16, 11): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
> The class is loaded from C:/Users/rutvik/.gradle/caches/transforms-3/347daadc4577e97ea182fd1bbd88604c/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class     
> e: C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\events\TopShouldStartLoadWithRequestEvent.kt: (18, 11): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
> The class is loaded from C:/Users/rutvik/.gradle/caches/transforms-3/347daadc4577e97ea182fd1bbd88604c/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class     
> e: C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\events\TopShouldStartLoadWithRequestEvent.kt: (28, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
> The class is loaded from C:/Users/rutvik/.gradle/caches/transforms-3/347daadc4577e97ea182fd1bbd88604c/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class     
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':react-native-webview:compileDebugKotlin'.
> > Compilation error. See log for more details
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 27s
> 
>     at makeError (C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\execa\index.js:174:9)
>     at C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\execa\index.js:278:16
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async runOnAllDevices (C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
>     at async Command.handleAction (C:\Users\rutvik\OneDrive\Desktop\app\BullAgritech\node_modules\@react-native-community\cli\build\index.js:192:9)
> info Run CLI with --verbose flag for more details.
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 
>

**Comment by joaocarmo** [comment]
You might want to take a look at this open issue: #2578. It seems the module has been compiled with an incompatible version of Kotlin.

Try adding an explicit version of Kotlin to your `android/build.gradle` file:

```gradle
buildscript {
    ext {
      kotlinVersion = "1.6.0"
      // ...
    }
    // ...
}
```

**Comment by rutvikER1999** [comment]
I have follow following solution >>> it worked for me
build.gradle
dependencies {
        classpath("com.android.tools.build:gradle:7.1.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("de.undercouch:gradle-download-task:5.0.1")
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.10" //add this line...take it from android studio

    }

app/build.gradle

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    //noinspection GradleDynamicVersion
    implementation 'com.github.mwiede:jsch:0.1.62' // add this line

**Comment by adhit7** [comment]
How did you solved the issue @rutvikER1999
